[version]
path = "src/view/__about__.py"

[build.targets.sdist]
only-include = ["src/", "_view.pyi"]

[build.targets.wheel]
packages = ["src/view"]

[build.targets.wheel.force-include]
"_view.pyi" = "_view.pyi"

[metadata.hooks.custom]
path = "hatch_build.py"
enable-by-default = true

[build.targets.wheel.hooks.scikit-build]
experimental = true

[envs.foo.scripts]
x = "python -c 'import view'"

[envs.hatch-test]
features = ["full"]
dev-mode = false
dependencies = [
    "coverage",
    "pytest",
    "pytest-memray",
    "pytest-asyncio",
]
platforms = ["linux", "macos"]

[envs.hatch-test.overrides]
platform.windows.dependencies = [
    "coverage",
    "pytest",
    "pytest-asyncio",
]
