site_name: view.py
site_url: https://view.zintensity.dev
repo_url: https://github.com/ZeroIntensity/view.py
repo_name: ZeroIntensity/view.py

nav:
    - index.md
    - Welcome: welcome.md
    - Getting Started:
          - Installation: getting-started/installation.md
          - Configuration: getting-started/configuration.md
          - Project Creation: getting-started/creating_a_project.md
    - Building Projects:
          - App Basics: building-projects/app_basics.md
          - URL Routing: building-projects/routing.md
          - Returning Responses: building-projects/responses.md
          - Taking Parameters: building-projects/parameters.md
          - Getting Request Data: building-projects/request_data.md
          - HTML Templating: building-projects/templating.md
          - Runtime Builds: building-projects/build_steps.md
          - Writing Documentation: building-projects/documenting.md
    - API Reference:
          - Types: reference/types.md
          - Utilities: reference/utils.md
          - Exceptions: reference/exceptions.md
          - Applications: reference/app.md
          - Configuration: reference/config.md
          - Routing: reference/routing.md
          - Responses: reference/responses.md
          - Templates: reference/templates.md

theme:
    name: null
    custom_dir: "html/"

markdown_extensions:
    - toc:
          permalink: true
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - admonition
    - pymdownx.details
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.superfences

plugins:
    - search
    - mkdocstrings:
          handlers:
              python:
                  paths: [src]
                  options:
                      show_root_heading: true
                      show_object_full_path: false
                      show_symbol_type_heading: true
                      show_symbol_type_toc: true
                      show_signature: true
                      seperate_signature: true
                      show_signature_annotations: true
                      signature_crossrefs: true
                      show_source: false
                      show_if_no_docstring: true
                      show_docstring_examples: false
