site_name: view.py
site_url: https://view.zintensity.dev
repo_url: https://github.com/ZeroIntensity/view.py
repo_name: ZeroIntensity/view.py

nav:
    - Home: index.md
    - Getting Started:
          - Installation: user-guide/getting-started/installation.md
          - Configuration: user-guide/getting-started/configuration.md
          - Project Creation: user-guide/getting-started/creating_a_project.md
    - Building Projects:
          - App Basics: user-guide/building-projects/app_basics.md
          - Routing: user-guide/building-projects/routing.md
          - Returning Responses: user-guide/building-projects/responses.md
          - Taking Parameters: user-guide/building-projects/parameters.md
          - Writing Documentation: user-guide/building-projects/documenting.md

theme:
    name: null
    custom_dir: "html/"

markdown_extensions:
    - toc:
          permalink: true
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - admonition
    - pymdownx.details
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
    - mkdocstrings:
          handlers:
              python:
                  paths: [src]
                  options:
                      show_root_heading: true
                      show_object_full_path: true
                      show_symbol_type_heading: true
                      show_symbol_type_toc: true
                      show_signature: true
                      seperate_signature: true
                      show_signature_annotations: true
                      signature_crossrefs: true
