site_name: view.py
site_url: https://view.zintensity.dev
repo_url: https://github.com/ZeroIntensity/view.py
repo_name: ZeroIntensity/view.py

nav:
    - Home: index.md
    - Getting Started:
        - Installation: getting-started/installation.md
        - Configuration: getting-started/configuration.md
        - Project Creation: getting-started/creating_a_project.md
    - Building Projects:
        - App Basics: building-projects/app_basics.md
        - Routing: building-projects/routing.md
        - Returning Responses: building-projects/responses.md
        - Taking Parameters: building-projects/parameters.md
        - HTML Templating: building-projects/templating.md
        - Writing Documentation: building-projects/documenting.md

theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: red
      accent: pink
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: red
      accent: pink
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: red
      accent: pink
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - admonition

plugins:
    - mkdocstrings:
          handlers:
              python:
                paths: [src]
                options:
                  show_object_full_path: true
                  show_symbol_type_heading: true
                  show_symbol_type_toc: true
                  seperate_signature: true
                  show_signature_annotations: true
                  signature_crossrefs: true
