site_name: view.py
site_url: https://view.zintensity.dev
repo_url: https://github.com/ZeroIntensity/view.py
repo_name: ZeroIntensity/view.py

nav:
    - Home: index.md
    - Getting Started:
        - Installation: getting-started/installation.md
        - Configuration: getting-started/configuration.md
        - Project Creation: getting-started/creating_a_project.md
    - Building Projects:
        - App Basics: building-projects/app_basics.md
        - Routing: building-projects/routing.md
        - Returning Responses: building-projects/responses.md
        - Taking Parameters: building-projects/parameters.md
        - HTML Templating: building-projects/templating.md
        - Writing Documentation: building-projects/documenting.md

theme: material
  #name: null
  #custom_dir: "html/"

markdown_extensions:
  - admonition

plugins:
    - mkdocstrings:
          handlers:
              python:
                paths: [src]
                options:
                  show_root_heading: true
                  show_object_full_path: true
                  show_symbol_type_heading: true
                  show_symbol_type_toc: true
                  seperate_signature: true
                  show_signature_annotations: true
                  signature_crossrefs: true
