[build-system]
requires = ["setuptools", "toml"]
build-backend = "setuptools.build_meta"

[project]
name = "view.py"
description = 'The Batteries-Detachable Web Framework.'
readme = "README.md"
requires-python = ">=3.8"
keywords = []
authors = [
  { name = "ZeroIntensity", email = "zintensitydev@gmail.com" },
]
classifiers = [
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: Implementation :: CPython",
]
dependencies = [
    "rich",
    "click",
    "typing_extensions",
    "ujson",
    "configzen",
    "aiofiles",
    "prompts.py",
]
dynamic = ["version", "license"]

[project.optional-dependencies]
databases = [
    "psycopg2-binary",
    "mysql-connector-python",
    "pymongo",
    "aiosqlite"
]
templates = ["beautifulsoup4", "jinja2", "mako", "django", "chameleon", "markdown"]
fancy = ["psutil", "plotext"]
servers = ["uvicorn[websockets]", "hypercorn", "daphne", "watchfiles"]
full = [
    "psutil",
    "plotext",
    "beautifulsoup4",
    "jinja2",
    "mako",
    "django",
    "chameleon",
    "attrs",
    "psycopg2-binary",
    "mysql-connector-python",
    "pymongo",
    "aiosqlite",
    "markdown",
    "uvicorn",
    "hypercorn",
    "daphne",
    "reactpy",
    "watchfiles"
]

[project.urls]
Documentation = "https://view.zintensity.dev"
Issues = "https://github.com/ZeroIntensity/view.py/issues"
Source = "https://github.com/ZeroIntensity/view.py"
Funding = "https://github.com/sponsors/ZeroIntensity"

[tool.hatch.version]
path = "src/view/__about__.py"

[tool.hatch.envs.docs]
dependencies = ["mkdocs", "mkdocstrings[python]", "mkdocs-material", "mkdocs-git-revision-date-localized-plugin"]

[tool.hatch.envs.docs.scripts]
build = "mkdocs build"
serve = "mkdocs serve"

[project.scripts]
view = "view.__main__:main"
view-admin = "view.__main__:main"

[tool.mypy]
exclude = ["src/view/databases.py", "src/view/components.py", "src/view/_codec.py"]
ignore_missing_imports = true
follow_imports = "skip"
enable_incomplete_feature = ["Unpack"]
